version: '3'

services:

  nginx:
    image: nginx:1.15.11-alpine
    container_name: moechat-nginx
    depends_on:
      - api
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/log/:/var/logs/
    ports:
      - 80:80
      - 443:443
      - 7001:7001
      - 7002:7002
    networks:
      - my-bridge

  api:
    image: moechat-service:0.0.5
    container_name: moechat-api
    depends_on:
      - redis
      - mysql
    volumes:
      - ./data/media:/media
    expose:
      - "8090"
      - "7001"
      - "7002"
    networks:
      - my-bridge
    restart: always
    command:
      - "--mysql.address=moechat-mysql"
      - "--redis.address=moechat-redis"

  redis:
    image: redis:4.0.14-alpine
    container_name: moechat-redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    networks:
      - my-bridge

  mysql:
    image: mysql:5.7
    container_name: moechat-mysql

    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/mysql:/var/lib/mysql
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    networks:
      - my-bridge
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Aa778899
      MYSQL_DATABASE: moechat


networks:
  my-bridge:
    driver: bridge